### build: docker compose -f docker-compose.cpu.yml build --no-cache
### start: docker compose -f docker-compose.cpu.yml up
### delete: docker compose -f docker-compose.cpu.yml down

version: "3.9"

services:
  obsidian-notes-gen:
    build: 
      context: .
      dockerfile: Dockerfile.cpu
    ports:
      - "7860:7860"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Only needed for Linux
    container_name: obsidian-notes-gen
    volumes:
      # Linux/Mac Downloads directory
      - ${HOME:-/home}/Downloads:/home/Downloads
      # Windows Downloads directory
      - ${USERPROFILE:-C:\Users}/Downloads:/windows/Downloads
      # For macOS, which may have Downloads in a different location
      - ${HOME}/Downloads:/mac/Downloads
      # chroma DB volume 
      - chromadb_data:${CHROMA_DB_PATH}
              
volumes:
  chromadb_data:
